language: go

go:
  - 1.8
  - tip

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

sudo: required

services:
  - docker

before_install:
  - make dependencies

script:
  - make test-coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - make push
